packages:
    - ./package
    - ./test
    - ./examples/*

autoInstallPeers: false
strictPeerDependencies: false

allowBuilds:
    "@swc/core": false
    esbuild: false
    sharp: false

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
    - "@apst/biome"
    - "@apst/tsconfig"
    - "@apst/tsdown"
    - "ts-vista"
